import { AbilityConstant, bundleManager, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { distributedKVStore } from '@kit.ArkData';

export let kvManager: distributedKVStore.KVManager;

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onCreate');
    let context = this.context
    try {
      let bundleName =
        bundleManager.getBundleInfoForSelfSync(bundleManager.BundleFlag.GET_BUNDLE_INFO_WITH_APPLICATION).name
      kvManager = distributedKVStore.createKVManager({
        context: context,
        bundleName: bundleName,
      })
      hilog.info(0x1799, 'testTag', '%{public}s', 'Succeeded in creating KVManager');
    } catch (err) {
      hilog.error(0x1799, 'testTag', 'Failed to create KVManager. Cause: %{public}s', JSON.stringify(err) ?? '');
    }
  }

  onDestroy(): void {
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onWindowStageCreate');

    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        hilog.error(0x1799, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err) ?? '');
        return;
      }
      hilog.info(0x1799, 'testTag', 'Succeeded in loading the content.');
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(0x1799, 'testTag', '%{public}s', 'Ability onBackground');
  }
}
